Copy in custom arp devices during installation if found

diff --git a/bin/arpscanconf b/bin/arpscanconf
--- a/bin/arpscanconf
+++ b/bin/arpscanconf
@@ -2,10 +2,12 @@
 
 ARPCOM="__ARP_SCAN_DEVICES__"
 STR="devices: \[\]\,"
-INPUT="/usr/local/MirrorCommandLine/etc/arp-devices.js"
+INPDIR="/usr/local/MirrorCommandLine/etc"
+DEFINP="${INPDIR}/arp-devices.js"
 
-[ -f ${INPUT} ] || {
-    echo "Missing input file ${INPUT}. Exiting."
+[ -f ${DEFINP} ] || {
+    echo "Missing default ARP devices input file ${DEFINP}."
+    echo "Exiting."
     exit 1
 }
 
@@ -13,7 +15,14 @@ find . -type f -name config-\*\.js | while read i
 do
     grep ${ARPCOM} $i > /dev/null && {
         b=`basename $i`
-        cat $i | sed -e "/${STR}/r ${INPUT}" -e "/${STR}/d" > /tmp/$b
+        config_name=`echo $b | sed -e "s/config-//" -e "s/.js//"`
+        if [ -f ${INPDIR}/arp-devices-${config_name}.js ]
+        then
+            ARPINP="${INPDIR}/arp-devices-${config_name}.js"
+        else
+            ARPINP="${DEFINP}"
+        fi
+        cat $i | sed -e "/${STR}/r ${ARPINP}" -e "/${STR}/d" > /tmp/$b
         grep -v ${ARPCOM} /tmp/$b > $i
         rm -f /tmp/$b
     }
