Move rmlist.txt to install folder

diff --git a/bin/ckemall b/bin/ckemall
--- a/bin/ckemall
+++ b/bin/ckemall
@@ -1,6 +1,15 @@
 #!/bin/bash
 
-cd /mnt/transcend/Pictures/MagicMirror
+MMDIR="/mnt/transcend/Pictures/MagicMirror"
+
+[ -d ${MMDIR} ] || {
+    MMDIR="/u/pictures/MagicMirror"
+    [ -d ${MMDIR} ] || {
+        echo "Cannot locate MagicMirror pics dir"
+        exit 1
+    }
+}
+cd ${MMDIR}
 
 while read i
 do
@@ -12,4 +21,4 @@ do
         j=`echo $i | sed -e "s/Artists\//Artists-ALL\//" -e "s/Models\//Playboy-ALL\//" -e "s/Photographers\//Photographers-ALL\//"`
         [ -L $j ] && echo $j
     fi
-done < $HOME/Pictures/rmlist.txt
+done < /usr/local/MirrorCommandLine/etc/rmlist.txt
diff --git a/bin/ckwhvnrm b/bin/ckwhvnrm
--- a/bin/ckwhvnrm
+++ b/bin/ckwhvnrm
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-cd /mnt/transcend/Pictures/Wallhaven
+MMDIR="/mnt/transcend/Pictures/Wallhaven"
+
+[ -d ${MMDIR} ] || {
+    MMDIR="/u/pictures/Wallhaven"
+    [ -d ${MMDIR} ] || {
+        echo "Cannot locate Wallhaven pics dir"
+        exit 1
+    }
+}
+cd ${MMDIR}
 
 while read i
 do
     [ -f $i ] && echo $i
-done < $HOME/Pictures/rmlist.txt
+done < /usr/local/MirrorCommandLine/etc/rmlist.txt
diff --git a/bin/rmempics b/bin/rmempics
--- a/bin/rmempics
+++ b/bin/rmempics
@@ -1,8 +1,17 @@
 #!/bin/bash
 
-cd /mnt/transcend/Pictures/MagicMirror
+MMDIR="/mnt/transcend/Pictures/MagicMirror"
+
+[ -d ${MMDIR} ] || {
+    MMDIR="/u/pictures/MagicMirror"
+    [ -d ${MMDIR} ] || {
+        echo "Cannot locate MagicMirror pics dir"
+        exit 1
+    }
+}
+cd ${MMDIR}
 
 while read img
 do
     rm -f $img
-done < $HOME/Pictures/rmlist.txt
+done < /usr/local/MirrorCommandLine/etc/rmlist.txt
diff --git a/bin/updmodel b/bin/updmodel
--- a/bin/updmodel
+++ b/bin/updmodel
@@ -2,15 +2,20 @@
 
 MNT_PT="/mnt/transcend/Pictures"
 MOD_DIR="${MNT_PT}/MagicMirror/Models"
-RMLIST="$HOME/Pictures/rmlist.txt"
+RMLIST="/usr/local/MirrorCommandLine/etc/rmlist.txt"
 
 # Use an associative array to map model names across sites
 declare -A model_sites
 
 [ -d ${MOD_DIR} ] || {
-    echo "$MOD_DIR does not exist or is not a directory. Exiting."
-    exit 1
+    MNT_PT="/u/pictures"
+    MOD_DIR="${MNT_PT}/MagicMirror/Models"
+    [ -d ${MOD_DIR} ] || {
+        echo "Cannot locate MagicMirror Models pics dir"
+        exit 1
+    }
 }
+
 cd ${MOD_DIR}
 TOP="${MNT_PT}/Wallhaven"
 MOD="${TOP}/Models"
