Update scripts to support both orientation folders for images

diff --git a/bin/gettopcounts b/bin/gettopcounts
--- a/bin/gettopcounts
+++ b/bin/gettopcounts
@@ -1,17 +1,25 @@
 #!/bin/bash
 
-ART="/mnt/transcend/Pictures/MagicMirror"
-
-[ -d ${ART} ] || {
-    echo "$ART does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${ART}
-rm -f counts.txt
-touch counts.txt
-for i in *
+PMM="${MNT_PT}/MagicMirror"
+
+for orient in landscape portrait
 do
+  [ -d ${PMM}/${orient} ] || continue
+  cd ${PMM}/${orient}
+  rm -f counts.txt
+  touch counts.txt
+  for i in *
+  do
     [ -d $i ] || continue
     count=`ls -1 $i | wc -l`
     echo "$count $i" >> counts.txt
+  done
 done
diff --git a/bin/mkalltop b/bin/mkalltop
--- a/bin/mkalltop
+++ b/bin/mkalltop
@@ -1,14 +1,21 @@
 #!/bin/bash
 
-ART="/mnt/transcend/Pictures/MagicMirror"
-
-[ -d ${ART} ] || {
-    echo "$ART does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${ART}
-for i in ../Wallhaven/*
+PMM="${MNT_PT}/MagicMirror"
+
+for orient in landscape portrait
 do
+  [ -d ${PMM}/${orient} ] || continue
+  cd ${PMM}/${orient}
+  for i in ../../Wallhaven/*
+  do
     [ -d "$i" ] || continue
     j=`basename "$i"`
     [ -d "$j" ] && {
@@ -17,5 +24,11 @@ do
     }
     echo "Creating $j"
     mkdir $j
-    updtoplinks $j
+    if [ "${orient}" == "landscape" ]
+    then
+      updtop -l $j
+    else
+      updtop $j
+    fi
+  done
 done
diff --git a/bin/mknewartist b/bin/mknewartist
--- a/bin/mknewartist
+++ b/bin/mknewartist
@@ -3,23 +3,40 @@
 TYPE="Artists"
 UPDSCRIPT="updartist"
 
-TYPEDIR="/mnt/transcend/Pictures/MagicMirror/${TYPE}"
-PICDIR="/usr/local/MirrorCommandLine/pics/${TYPE}"
-
-[ -d ${PICDIR} ] || mkdir -p ${PICDIR}
-[ -d ${TYPEDIR} ] || {
-  TYPEDIR="/u/pictures/MagicMirror/${TYPE}"
-  [ -d ${TYPEDIR} ] || {
-    echo "$TYPEDIR does not exist or is not a directory. Exiting."
-    exit 1
-  }
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
+PMM="${MNT_PT}/MagicMirror"
 
 portrait=
+orientation="portrait"
 [ "$1" == "-l" ] && {
     portrait="-l"
+    orientation="landscape"
     shift
 }
+
+PICDIR="/usr/local/MirrorCommandLine/pics-${orientation}"
+[ -d ${PICDIR} ] || mkdir -p ${PICDIR}
+
+for orient in ${orientation}
+do
+  TYPEDIR="${PMM}/${orient}/${TYPE}"
+  PICDIR="${PICDIR}/${TYPE}"
+  [ -d ${PICDIR} ] || mkdir -p ${PICDIR}
+  [ -d ${TYPEDIR} ] || {
+    TYPEDIR="/v/pictures/MagicMirror/${orient}/${TYPE}"
+    [ -d ${TYPEDIR} ] || {
+        echo "$TYPEDIR does not exist or is not a directory. Exiting."
+        exit 1
+    }
+  }
+done
 
 cd ${TYPEDIR}
 for i in $*
diff --git a/bin/mmfavs b/bin/mmfavs
--- a/bin/mmfavs
+++ b/bin/mmfavs
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-MAG="/mnt/transcend/Pictures/MagicMirror"
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
+}
+MAG="${MNT_PT}/MagicMirror"
 TOP="/mnt/transcend/Pictures/Wallhaven"
 ART=${TOP}/Artists
 PHO=${TOP}/Photographers
@@ -10,39 +18,68 @@ PEN=${MOD}/Penthouse
 
 FAVS="Ali_Rose Alisa_I Carisha Corinna David_Dubnitskiy Dmitry_Borisov Heidi_Romanova Helly_von_Valentine Igor_Viushkin Jenya Li_Moon Martina_Mink Nata_Lee Natalia_Andreeva Niemira Priscilla_Huggins Sakimichan Stefan_Soell Tuigirl"
 
-cd $MAG
-
-for i in $FAVS
+for orient in landscape portrait
 do
+  [ -d ${MAG}/${orient} ] || continue
+  cd ${MAG}/${orient}
+
+  for i in $FAVS
+  do
     echo "Creating/updating $i MagicMirror background pics"
     [ -d $TOP/$i ] && {
         echo "Found $i in $TOP"
         [ -d $i ] || mkdir $i
-        updtoplinks $i
+        if [ "${orient}" == "landscape" ]
+        then
+          updtop -l "$i"
+        else
+          updtop "$i"
+        fi
         continue
     }
     [ -d $ART/$i ] && {
         echo "Found $i in $ART"
         [ -d Artists/$i ] || mkdir Artists/$i
-        updartistlinks $i
+        if [ "${orient}" == "landscape" ]
+        then
+          updartist -l "$i"
+        else
+          updartist "$i"
+        fi
         continue
     }
     [ -d $MOD/$i ] && {
         echo "Found $i in $MOD"
         [ -d Models/$i ] || mkdir Models/$i
-        updmodellinks $i
+        if [ "${orient}" == "landscape" ]
+        then
+          updmodel -l "$i"
+        else
+          updmodel "$i"
+        fi
         continue
     }
     [ -d $PHO/$i ] && {
         echo "Found $i in $PHO"
         [ -d Photographers/$i ] || mkdir Photographers/$i
-        updphotographerlinks $i
+        if [ "${orient}" == "landscape" ]
+        then
+          updphotographer -l "$i"
+        else
+          updphotographer "$i"
+        fi
         continue
     }
     [ -d $PLA/$i ] && {
         echo "Found $i in $PLA"
         [ -d Playboy/$i ] || mkdir Playboy/$i
-        updplayboylinks $i
+        if [ "${orient}" == "landscape" ]
+        then
+          updplayboy -l "$i"
+        else
+          updplayboy "$i"
+        fi
         continue
     }
+  done
 done
diff --git a/bin/updallartists b/bin/updallartists
--- a/bin/updallartists
+++ b/bin/updallartists
@@ -1,14 +1,28 @@
 #!/bin/bash
 
-ART_DIR="/mnt/transcend/Pictures/MagicMirror/Artists"
-
-[ -d ${ART_DIR} ] || {
-    echo "$ART_DIR does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${ART_DIR}
+PMM="${MNT_PT}/MagicMirror"
 
-for folder in *
+for orient in landscape portrait
 do
-    updartist "$folder"
+  MOD_DIR="${PMM}/${orient}/Artists"
+  [ -d ${MOD_DIR} ] || continue
+  cd ${MOD_DIR}
+
+  for folder in *
+  do
+    if [ "${orient}" == "landscape" ]
+    then
+      updartist -l "$folder"
+    else
+      updartist "$folder"
+    fi
+  done
 done
diff --git a/bin/updallphotographers b/bin/updallphotographers
--- a/bin/updallphotographers
+++ b/bin/updallphotographers
@@ -1,14 +1,28 @@
 #!/bin/bash
 
-PHO_DIR="/mnt/transcend/Pictures/MagicMirror/Photographers"
-
-[ -d ${PHO_DIR} ] || {
-    echo "$PHO_DIR does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${PHO_DIR}
+PMM="${MNT_PT}/MagicMirror"
 
-for folder in *
+for orient in landscape portrait
 do
-    updphotographer "$folder"
+  MOD_DIR="${PMM}/${orient}/Photographers"
+  [ -d ${MOD_DIR} ] || continue
+  cd ${MOD_DIR}
+
+  for folder in *
+  do
+    if [ "${orient}" == "landscape" ]
+    then
+      updphotographer -l "$folder"
+    else
+      updphotographer "$folder"
+    fi
+  done
 done
diff --git a/bin/updalltop b/bin/updalltop
--- a/bin/updalltop
+++ b/bin/updalltop
@@ -1,22 +1,35 @@
 #!/bin/bash
 
-TOP_DIR="/mnt/transcend/Pictures/MagicMirror"
-
-[ -d ${TOP_DIR} ] || {
-    echo "$TOP_DIR does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${TOP_DIR}
+PMM="${MNT_PT}/MagicMirror"
 
-for folder in *
+for orient in landscape portrait
 do
+  MOD_DIR="${PMM}/${orient}"
+  [ -d ${MOD_DIR} ] || continue
+  cd ${MOD_DIR}
+
+  for folder in *
+  do
     case $folder in
         Artists | Artists-ALL | JAV | JAV-ALL | Models | Models-ALL | Photographers | Photographers-ALL | Playboy-ALL)
             continue
             ;;
         *)
-            echo "Updating $folder"
-            updtop "$folder"
+            if [ "${orient}" == "landscape" ]
+            then
+              updtop -l "$folder"
+            else
+              updtop "$folder"
+            fi
             ;;
     esac
+  done
 done
diff --git a/bin/updartist b/bin/updartist
--- a/bin/updartist
+++ b/bin/updartist
@@ -1,21 +1,36 @@
 #!/bin/bash
 
 MNT_PT="/mnt/transcend/Pictures"
-ART_DIR="${MNT_PT}/MagicMirror/Artists"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
+}
+PMM="${MNT_PT}/MagicMirror"
+
+portrait=1
+orientation="portrait"
+[ "$1" == "-l" ] && {
+    portrait=
+    orientation="landscape"
+    shift
+}
+
+MOD_DIR="${MNT_PT}/MagicMirror/${orientation}/Artists"
 RMLIST="/usr/local/MirrorCommandLine/etc/rmlist.txt"
 
-# Use an associative array to map artist names across sites
-declare -A artist_sites
-
-[ -d ${ART_DIR} ] || {
-  MNT_PT="/u/pictures"
-  ART_DIR="${MNT_PT}/MagicMirror/Artists"
-  [ -d ${ART_DIR} ] || {
-    echo "$ART_DIR does not exist or is not a directory. Exiting."
-    exit 1
-  }
+[ -d ${MOD_DIR} ] || {
+    MNT_PT="/v/pictures"
+    MOD_DIR="${MNT_PT}/MagicMirror/${orientation}/Artists"
+    [ -d ${MOD_DIR} ] || {
+        echo "Cannot locate MagicMirror Artists pics dir"
+        exit 1
+    }
 }
-cd ${ART_DIR}
+
+cd ${MOD_DIR}
 TOP="${MNT_PT}/Wallhaven"
 MOD="${TOP}/Models"
 ART="${TOP}/Artists"
@@ -51,12 +66,6 @@ isportrait() {
     return $port
 }
 
-portrait=1
-[ "$1" == "-l" ] && {
-    portrait=
-    shift
-}
-
 [ "$1" ] || {
     echo "Use 'mmupdall' to update all folders."
     echo "This script requires a folder or folders as arguments."
@@ -83,11 +92,11 @@ do
                     rm -f $subimg
                     continue
                 }
-                for ADIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
+                for MDIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
                 do
-                    [ -f $ADIR/$folder/$subimg ] && {
+                    [ -f $MDIR/$folder/$subimg ] && {
                         rm -f $subimg
-                        cp $ADIR/$folder/$subimg $subimg
+                        cp $MDIR/$folder/$subimg $subimg
                         break
                     }
                 done
@@ -98,17 +107,17 @@ do
                 rm -f $img
                 continue
             }
-            for ADIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
+            for MDIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
             do
-                [ -f $ADIR/$folder/$img ] && {
+                [ -f $MDIR/$folder/$img ] && {
                     rm -f $img
-                    cp $ADIR/$folder/$img .
+                    cp $MDIR/$folder/$img .
                     break
                 }
             done
         fi
     done
-    cd ${ART_DIR}
+    cd ${MOD_DIR}
 done
 
 # Identify any newly added files and copy them
@@ -117,33 +126,12 @@ do
     [ "$folder" == "*" ] && continue
     [ "$folder" == "Unused" ] && continue
     [ -d $folder ] || continue
-    # In case we need this in the future, follow the example of model sites
-    case $folder in
-        Jenya)
-            artist_sites[$ELITE]="Eugenia_Diordiychuk"
-            ;;
-        Natalia_Andreeva)
-            artist_sites[$ELITE]="Delilah_G"
-            artist_sites[$KIND]="Natalia_A"
-            ;;
-        Niemira)
-            artist_sites[$ELITE]="Niemira_A"
-            ;;
-        Priscilla_Huggins)
-            artist_sites[$ELITE]="Priscilla_Huggins_Ortiz"
-            ;;
-        *)
-            ;;
-    esac
-    for ADIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
+    for MDIR in $MOD $ART $JAV $PHO $KIND $PLA $PEN $DRO $TOP $ELITE
     do
       chkfolder=$folder
-      [ "${artist_sites[$ADIR]}" ] && {
-              chkfolder="${artist_sites[$ADIR]}"
-      }
-      [ -d $ADIR/$chkfolder ] && {
-        echo "Checking $ADIR/$chkfolder for newly added files"
-        cd $ADIR/$chkfolder
+      [ -d $MDIR/$chkfolder ] && {
+        echo "Checking $MDIR/$chkfolder for newly added files"
+        cd $MDIR/$chkfolder
         for img in *
         do
             [ "$img" == "*" ] && continue
@@ -152,13 +140,11 @@ do
             [ "$img" == "Description.txt" ] && continue
             if [ -d "$img" ]
             then
-                [ -d ${ART_DIR}/$folder/$img ] || mkdir -p ${ART_DIR}/$folder/$img
+                [ -d ${MOD_DIR}/$folder/$img ] || mkdir -p ${MOD_DIR}/$folder/$img
                 for subimg in $img/*
                 do
                     [ "$subimg" == "$img/*" ] && continue
-                    [ -L ${ART_DIR}/$folder/$subimg ] && {
-                        rm -f ${ART_DIR}/$folder/$subimg
-                    }
+                    [ -L ${MOD_DIR}/$folder/$subimg ] && rm -f ${MOD_DIR}/$folder/$subimg
                     grep $subimg $RMLIST > /dev/null && {
                         rm -f $subimg
                         continue
@@ -166,16 +152,16 @@ do
                     if isportrait $subimg
                     then
                         [ "${portrait}" ] && {
-                          cp $ADIR/$chkfolder/$subimg ${ART_DIR}/$folder/$subimg
+                          cp $MDIR/$chkfolder/$subimg ${MOD_DIR}/$folder/$subimg
                         }
                     else
                         [ "${portrait}" ] || {
-                          cp $ADIR/$chkfolder/$subimg ${ART_DIR}/$folder/$subimg
+                          cp $MDIR/$chkfolder/$subimg ${MOD_DIR}/$folder/$subimg
                         }
                     fi
                 done
             else
-                [ -L ${ART_DIR}/$folder/$img ] && rm -f ${ART_DIR}/$folder/$img
+                [ -L ${MOD_DIR}/$folder/$img ] && rm -f ${MOD_DIR}/$folder/$img
                 grep $img $RMLIST > /dev/null && {
                     rm -f $img
                     continue
@@ -183,17 +169,17 @@ do
                 if isportrait $img
                 then
                     [ "${portrait}" ] && {
-                      cp $ADIR/$chkfolder/$img ${ART_DIR}/$folder/$img
+                      cp $MDIR/$chkfolder/$img ${MOD_DIR}/$folder/$img
                     }
                 else
                     [ "${portrait}" ] || {
-                      cp $ADIR/$chkfolder/$img ${ART_DIR}/$folder/$img
+                      cp $MDIR/$chkfolder/$img ${MOD_DIR}/$folder/$img
                     }
                 fi
             fi
         done
-        cd ${ART_DIR}
+        cd ${MOD_DIR}
       }
     done
-    cd ${ART_DIR}
+    cd ${MOD_DIR}
 done
