First pass at image scripts support for both orientations, Models only first

diff --git a/bin/mkallmodels b/bin/mkallmodels
--- a/bin/mkallmodels
+++ b/bin/mkallmodels
@@ -1,14 +1,21 @@
 #!/bin/bash
 
-ART="/mnt/transcend/Pictures/MagicMirror/Models"
-
-[ -d ${ART} ] || {
-    echo "$ART does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${ART}
-for i in ../../Wallhaven/Models/*
+PMM="${MNT_PT}/MagicMirror"
+
+for orient in landscape portrait
 do
+  [ -d ${PMM}/${orient}/Models ] || continue
+  cd ${PMM}/${orient}/Models
+  for i in ../../../Wallhaven/Models/*
+  do
     [ -d "$i" ] || continue
     j=`basename "$i"`
     [ -d "$j" ] && {
@@ -17,5 +24,11 @@ do
     }
     echo "Creating $j"
     mkdir $j
-    updmodellinks $j
+    if [ "${orient}" == "landscape" ]
+    then
+      updmodellinks -l $j
+    else
+      updmodellinks $j
+    fi
+  done
 done
diff --git a/bin/tomodellinks b/bin/tomodellinks
--- a/bin/tomodellinks
+++ b/bin/tomodellinks
@@ -1,24 +1,31 @@
 #!/bin/bash
 
-ART_DIR="/mnt/transcend/Pictures/MagicMirror/Models"
-
-[ -d ${ART_DIR} ] || {
-    echo "$ART_DIR does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${ART_DIR}
-#TOP="/Volumes/Seagate_8TB/Pictures/Work/Wallhaven/Models"
-TOP="../../Wallhaven"
+PMM="${MNT_PT}/MagicMirror"
+TOP="../../../Wallhaven"
 ART="${TOP}/Artists"
 MOD="${TOP}/Models"
 PHO="${TOP}/Photographers"
 PLA="${MOD}/Playboy"
 PEN="${MOD}/Penthouse"
 DRO="${MOD}/Photodromm"
-KND="../../KindGirls"
+KND="../../../KindGirls"
 
-for folder in *
+for orient in landscape portrait
 do
+  MOD_DIR="${PMM}/${orient}/Models"
+  [ -d ${MOD_DIR} ] || continue
+  cd ${MOD_DIR}
+
+  for folder in *
+  do
     [ -d $folder ] || continue
     cd $folder
     for img in *
@@ -34,4 +41,5 @@ do
         done
     done
     cd ..
+  done
 done
diff --git a/bin/updallmodels b/bin/updallmodels
--- a/bin/updallmodels
+++ b/bin/updallmodels
@@ -1,14 +1,28 @@
 #!/bin/bash
 
-MOD_DIR="/mnt/transcend/Pictures/MagicMirror/Models"
-
-[ -d ${MOD_DIR} ] || {
-    echo "$MOD_DIR does not exist or is not a directory. Exiting."
-    exit 1
+MNT_PT="/mnt/transcend/Pictures"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
 }
-cd ${MOD_DIR}
+PMM="${MNT_PT}/MagicMirror"
 
-for folder in *
+for orient in landscape portrait
 do
-    updmodel "$folder"
+  MOD_DIR="${PMM}/${orient}/Models"
+  [ -d ${MOD_DIR} ] || continue
+  cd ${MOD_DIR}
+
+  for folder in *
+  do
+    if [ "${orient}" == "landscape" ]
+    then
+      updmodel -l "$folder"
+    else
+      updmodel "$folder"
+    fi
+  done
 done
diff --git a/bin/updmodel b/bin/updmodel
--- a/bin/updmodel
+++ b/bin/updmodel
@@ -1,15 +1,32 @@
 #!/bin/bash
 
 MNT_PT="/mnt/transcend/Pictures"
-MOD_DIR="${MNT_PT}/MagicMirror/Models"
+[ -d ${MNT_PT} ] || {
+    MNT_PT="/u/pictures"
+    [ -d ${MNT_PT} ] || {
+        echo "Cannot locate mount point for images"
+        exit 1
+    }
+}
+PMM="${MNT_PT}/MagicMirror"
+
+portrait=1
+orientation="portrait"
+[ "$1" == "-l" ] && {
+    portrait=
+    orientation="landscape"
+    shift
+}
+
+MOD_DIR="${MNT_PT}/MagicMirror/${orientation}/Models"
 RMLIST="/usr/local/MirrorCommandLine/etc/rmlist.txt"
 
 # Use an associative array to map model names across sites
 declare -A model_sites
 
 [ -d ${MOD_DIR} ] || {
-    MNT_PT="/u/pictures"
-    MOD_DIR="${MNT_PT}/MagicMirror/Models"
+    MNT_PT="/v/pictures"
+    MOD_DIR="${MNT_PT}/MagicMirror/${orientation}/Models"
     [ -d ${MOD_DIR} ] || {
         echo "Cannot locate MagicMirror Models pics dir"
         exit 1
@@ -50,12 +67,6 @@ isportrait() {
         return $port
     }
     return $port
-}
-
-portrait=1
-[ "$1" == "-l" ] && {
-    portrait=
-    shift
 }
 
 [ "$1" ] || {
