Present a menu for ALSA device selection

diff --git a/bin/set_asound_conf b/bin/set_asound_conf
--- a/bin/set_asound_conf
+++ b/bin/set_asound_conf
@@ -77,37 +77,102 @@ then
     sudo rm -f ${ASOUND}.orig
   }
 else
-  INPUT=`grep ${INGREP} ${CARDS} | grep -i "Webcam" | awk ' { print $1 } '`
-  [ "${INPUT}" ] || {
-    INPUT=`grep ${INGREP} ${CARDS} | grep "Audio Device" | awk ' { print $1 } '`
-  }
-  [ "${INPUT}" ] && {
-    INPUT=`echo ${INPUT} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
-  }
-  OUTPUT=`grep ${OUTGREP} ${CARDS} | grep "DAC" | awk ' { print $1 } '`
-  [ "${OUTPUT}" ] || {
-    OUTPUT=`grep ${OUTGREP} ${CARDS} | grep "Audio Device" | awk ' { print $1 } '`
-  }
-  [ "${OUTPUT}" ] && {
-    OUTPUT=`echo ${OUTPUT} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
-  }
-  # If audio input or output device could not be detected just use 0 and 1
-  [ "${INPUT}" ] || {
-    if [ "${OUTPUT}" == "0" ]
-    then
-      INPUT=1
-    else
-      INPUT=0
-    fi
-  }
-  [ "${OUTPUT}" ] || {
-    if [ "${INPUT}" == "0" ]
-    then
-      OUTPUT=1
-    else
-      OUTPUT=0
-    fi
-  }
+  # Present a selection dialog to allow user to choose audio input and output
+  echo ""
+  device_options=()
+  while read entry
+  do
+    devnum=`echo ${entry} | awk ' { print $1 } '`
+    [ "${devnum}" -eq "${devnum}" ] 2> /dev/null || continue
+    device=`echo ${entry} | awk -F ':' ' { print $2 } '`
+    device=`echo ${device} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
+    device_options+=("${device}")
+  done < <(cat ${CARDS})
+  device_options+=("Select For Me" "None" "Quit")
+  PS3="${BOLD}Please enter the device you wish to use for AUDIO OUTPUT (numeric or text): ${NORMAL}"
+  select opt in "${device_options[@]}"
+  do
+    case "$opt,$REPLY" in
+      [0-9]*,*|*,[0-9]*)
+          OUTPUT=${REPLY}
+          ((OUTPUT--))
+          break
+          ;;
+      "Select For Me",*|*,"Select For Me"|"select for me",*|*,"select for me")
+          OUTPUT=`grep ${OUTGREP} ${CARDS} | grep "DAC" | awk ' { print $1 } '`
+          [ "${OUTPUT}" ] || {
+            OUTPUT=`grep '\[Headphones' ${CARDS} | awk ' { print $1 } '`
+          }
+          [ "${OUTPUT}" ] || {
+            OUTPUT=`grep ${OUTGREP} ${CARDS} | grep "Audio Device" | awk ' { print $1 } '`
+          }
+          [ "${OUTPUT}" ] && {
+            OUTPUT=`echo ${OUTPUT} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
+          }
+          [ "${OUTPUT}" ] || OUTPUT=1
+          ;;
+      "None",*|*,"None"|"none",*|*,"none")
+          OUTPUT=1
+          break
+          ;;
+      "Quit",*|*,"Quit"|"quit",*|*,"quit")
+          exit 0
+          ;;
+      *)
+          printf "\nInvalid entry. Please try again"
+          printf "\nEnter either a number or text of one of the menu entries\n"
+          ;;
+    esac
+  done
+
+  echo ""
+  PS3="${BOLD}Please enter the device you wish to use for AUDIO INPUT (numeric or text): ${NORMAL}"
+  select opt in "${device_options[@]}"
+  do
+    case "$opt,$REPLY" in
+      [0-9]*,*|*,[0-9]*)
+          INPUT=${REPLY}
+          ((INPUT--))
+          break
+          ;;
+      "Select For Me",*|*,"Select For Me"|"select for me",*|*,"select for me")
+          INPUT=`grep ${INGREP} ${CARDS} | grep "Webcam" | awk ' { print $1 } '`
+          [ "${INPUT}" ] || {
+            INPUT=`grep '\[Microphone' ${CARDS} | awk ' { print $1 } '`
+          }
+          [ "${INPUT}" ] || {
+            INPUT=`grep ${INGREP} ${CARDS} | grep "Audio Device" | awk ' { print $1 } '`
+          }
+          [ "${INPUT}" ] && {
+            INPUT=`echo ${INPUT} | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'`
+          }
+          [ "${INPUT}" ] || {
+            if [ "${OUTPUT}" == "0" ]
+            then
+              INPUT=1
+            else
+              INPUT=0
+            fi
+          }
+          ;;
+      "None",*|*,"None"|"none",*|*,"none")
+          if [ "${OUTPUT}" == "0" ]
+          then
+            INPUT=1
+          else
+            INPUT=0
+          fi
+          break
+          ;;
+      "Quit",*|*,"Quit"|"quit",*|*,"quit")
+          exit 0
+          ;;
+      *)
+          printf "\nInvalid entry. Please try again"
+          printf "\nEnter either a number or text of one of the menu entries\n"
+          ;;
+    esac
+  done
 
   # Generate a new asound.conf from the template
   cat ${ASOUND_TMPL} | \
@@ -150,18 +215,12 @@ else
             echo "${ASOUND} is identical to a generated asound.conf. No need to update."
           }
         else
-          if [ -f ${ASOUND}.orig ]
-          then
-            [ "${QUT}" ] || {
-              echo "Copying ${ASOUND} to ${ASOUND}.bak$$"
-            }
-            sudo cp ${ASOUND} ${ASOUND}.bak$$
-          else
+          [ -f ${ASOUND}.orig ] || {
             [ "${QUT}" ] || {
               echo "Copying original ${ASOUND} to ${ASOUND}.orig"
             }
             sudo cp ${ASOUND} ${ASOUND}.orig
-          fi
+          }
           [ "${QUT}" ] || {
             echo "Installing generated asound.conf as ${ASOUND}"
           }
