Initial pass at RPM build

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -33,12 +33,12 @@ PKG_REL=${RELEASE}
 export DISPLAY=:0
 
 get_available_packages() {
-  for debs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.deb
+  for pkgs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}
   do
-    [ "${debs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.deb" ] || {
-      for pkg in ${debs}
+    [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}/*.${SUF}" ] || {
+      for pkg in ${pkgs}
       do
-        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}.deb//"` 
+        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}.${SUF}//"` 
         PKG_AVAILABLE="${PKG_AVAILABLE} ${pkgname}"
       done
     }
@@ -86,6 +86,18 @@ check_package_names() {
     PKG_NAMES="MirrorCommand ${pkg_names_tmp}"
   }
 }
+
+debian=
+have_apt=`type -p apt`
+have_dpkg=`type -p dpkg`
+have_rpm=`type -p rpm`
+have_yum=`type -p yum`
+[ -f /etc/os-release ] && . /etc/os-release
+[ "${ID_LIKE}" == "debian" ] && debian=1
+[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+
+SUF=deb
+[ "${debian}" ] || SUF=rpm
 
 get_available_packages
 [ "$PKG_AVAILABLE}" ] || {
@@ -180,14 +192,14 @@ xhost +si:localuser:root
 
 for PKG_NAME in ${PKG_NAMES}
 do
-  DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb"
+  DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
   [ -f "${DEB}" ] || {
-    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb not found."
-    for debs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb
+    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF} not found."
+    for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
     do
-      [ "${debs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb" ] || {
+      [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
         echo "Found existing packages:"
-        echo "${debs}"
+        echo "${pkgs}"
       }
     done
     echo ""
