Wrap type -p command checks in if-then-else to prevent ERR triggering exit with set -e execution

diff --git a/pkg/debian/postinst b/pkg/debian/postinst
--- a/pkg/debian/postinst
+++ b/pkg/debian/postinst
@@ -6,13 +6,13 @@
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#        * <postinst> 'configure' <most-recently-configured-version>
+#        * <old-postinst> 'abort-upgrade' <new version>
+#        * <conflictor's-postinst> 'abort-remove' 'in-favour' <package>
 #          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <postinst> 'abort-remove'
+#        * <deconfigured's-postinst> 'abort-deconfigure' 'in-favour'
+#          <failed-install-package> <version> 'removing'
 #          <conflicting-package> <version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
@@ -40,7 +40,6 @@ case "$1" in
         [ -f ${MM}/etc/mirror_start.sh ] && {
           [ -f mirror_start ] || ln -s ${MM}/etc/mirror_start.sh mirror_start
         }
-        # This fails but why
         # inst_vcgencmd=`type -p vcgencmd`
         # [ "${inst_vcgencmd}" ] || {
         #     [ -f vcgencmd ] || ln -s ${MM}/bin/vcgencmd vcgencmd
@@ -126,7 +125,12 @@ case "$1" in
               ${MM}/bin/set_roon_conf
             }
             # Fixup the ARP Scan devices used by MMM-MacAddressScan module
-            inst_arpscan=`type -p arp-scan`
+            if type -p arp-scan
+            then
+              inst_arpscan=1
+            else
+              inst_arpscan=
+            fi
             [ "${inst_arpscan}" ] && {
               [ -x ${MM}/bin/arps2mm ] && {
                 ${MM}/bin/arps2mm > ${MM}/etc/arp-devices.js
@@ -345,9 +349,19 @@ case "$1" in
 
         [ "${MMHOME}" ] && {
             # Setup PM2 if not already configured
-            inst_pm2=`type -p pm2`
+            if type -p pm2
+            then
+              inst_pm2=1
+            else
+              inst_pm2=
+            fi
             [ "${inst_pm2}" ] || npm install pm2@latest -g > /dev/null 2>&1
-            inst_pm2=`type -p pm2`
+            if type -p pm2
+            then
+              inst_pm2=1
+            else
+              inst_pm2=
+            fi
             [ "${inst_pm2}" ] && {
                 sudo -u ${USER} pm2 list | grep MagicMirror > /dev/null && {
                   sudo -u ${USER} pm2 --silent describe MagicMirror && {
@@ -365,7 +379,12 @@ case "$1" in
                 pm2_startup=`sudo -u ${USER} pm2 startup | tail -n 1`
                 # Check to see if we can get the OS package name (Ubuntu)
                 fix_startup=
-                have_lsb=`type -p lsb_release`
+                if type -p lsb_release
+                then
+                  have_lsb=1
+                else
+                  have_lsb=
+                fi
                 if [ "${have_lsb}" ]
                 then
                   if [ $(which lsb_release| wc -l) >0 ]; then
@@ -433,7 +452,7 @@ case "$1" in
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "postinst called with unknown argument: $1" >&2
         exit 1
     ;;
 esac
