Move npm from dependency to preinstall script install with n

diff --git a/pkg/debian/preinst b/pkg/debian/preinst
--- a/pkg/debian/preinst
+++ b/pkg/debian/preinst
@@ -7,6 +7,7 @@ set -e
 
 case "$1" in
     install|upgrade)
+        export PATH=/usr/local/bin:$PATH
         MMHOME="/home/pi/MagicMirror"
         USER=
         GROUP=
@@ -67,14 +68,32 @@ case "$1" in
                       }
                       [ -d /usr/local ] || mkdir /usr/local
                       cd /usr/local
+                      inst_npm=`type -p npm`
+                      [ "${inst_npm}" ] || {
+                          echo "Installing npm in /usr/local/..."
+                          curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o /tmp/n
+                          bash /tmp/n lts
+                          npm install -g n
+                      }
                       git clone https://github.com/MichMich/MagicMirror > /dev/null
                       GROUP=`id -g -n ${USER}`
                       chown -R ${USER}:${GROUP} MagicMirror
                       cd MagicMirror
                       MMHOME="/usr/local/MagicMirror"
-                      echo "Installing MagicMirror in /usr/local/MagicMirror"
-                      sudo -u ${USER} npm install > /dev/null 2>&1
-                      # sudo -u ${USER} cp config/config.js.sample config/config.js
+                      inst_npm=`type -p npm`
+                      if [ "${inst_npm}" ]
+                      then
+                          echo "Installing MagicMirror in /usr/local/MagicMirror"
+                          sudo -u ${USER} npm install > /dev/null 2>&1
+                      else
+                          echo "Unable to locate npm in the execution path."
+                          echo "Install npm and run the MagicMirror installation"
+                          echo "by executing the commands:"
+                          echo ""
+                          echo "cd /usr/local/MagicMirror"
+                          echo "sudo -u ${USER} npm install"
+                          echo ""
+                      fi
                       break
                       ;;
                   [Nn]*)
